require('Libs.LuaCore.Tests.MathUtilsTests')
require('Libs.LuaCore.Tests.StringUtilsTests')
require('Libs.LuaCore.Tests.TableUtilsTests')
require('Libs.LuaCore.Tests.WowUtilsTests')
require('Libs.LuaCore.Tests.TimeUtilsTests')